### ISSUE TITLE
Requires iTerm

### ISSUE THREAD

**Issue by gerb030** [thijsdezoete/macos-docker-tray#1]
Shell command to Docker images requires iTerm. If you are running the default MacOS Terminal, you can't use the Shell command and no error is visible.

**Comment by thijsdezoete** [comment]
Thanks for your feedback!
I agree that's unwanted behaviour. I've released v0.3 which contains the fix for this.

https://github.com/thijsdezoete/macos-docker-tray/releases/tag/0.3
